### ISSUE TITLE
Meta requests

### ISSUE THREAD

**Issue by thirdman** [thirdman/infinft-project#4]
### Custom Meta 
- custom meta PUBLIC 
- custom meta PRIVATE

These should be able to be created and retrieved for a token, (private only if you are the owner). 
- As i understand, stored as a json on ipfs. 
- this would allow for an infinate variety of use cases.

---
### META

- [ ] 'isInfiftToken' or something like 'hasOnchain': Possibly this is redundant, but when users are creating their own contracts I'd love a way of discovering whether the token is an INFINFT generated one - in order to be able to query the additional onchain meta/custom meta. An example is in Flawnt.me.
- [ ] Background color: Opensea uses this in thier PI, and is particularly useful for SVG and images that have a transparent background. Cryptokitties does this well.

---
### Ideas:
- [ ] Exhibition description: Possible use for galleries where you want to describe the set of tokens this one belongs to?

---
### Questions

USER CONTRACT
Is there a way to store the deployed contract icon? How does opensea etc do this?
